function  parsave(fName, errorRateASGE, errorRateOpti, ...
    errorRateOptiBest, fValueNew, fValueBest, xBest, nuBest, tauBest, ...
    loglik)
% save data
    save(fName, 'errorRateASGE', 'errorRateOpti', 'errorRateOptiBest', ...
        'fValueNew', 'fValueBest', 'xBest', 'nuBest', 'tauBest', ...
        'loglik');
end