function  parsave(fName, errorRateASGE, errorRateOpti, ...
    errorRateOptiBest, fValueNew, fValueBest, xBest, nuBest, tauBest, ...
    fValue0, fValue1)
% save data
    save(fName, 'errorRateASGE', 'errorRateOpti', 'errorRateOptiBest', ...
        'fValueNew', 'fValueBest', 'xBest', 'nuBest', 'tauBest', ...
        'fValue0', 'fValue1');
end