function  parsave(fName, errorRateASGE, errorRateOpti, xBest, ...
    nuBest, tauBest, tauBestc, xHat0, nuHat0, tauHat0, tauHat0c, ...
    loglikASGE, loglikASGEc, loglikOpti, loglikOptic);
% save data
save(fName, 'errorRateASGE', 'errorRateOpti', 'xBest', 'nuBest', ...
    'tauBest', 'tauBestc', 'xHat0', 'nuHat0', 'tauHat0', 'tauHat0c', ...
    'loglikASGE', 'loglikASGEc', 'loglikOpti', 'loglikOptic');
end